name: airmaster
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.3.0
  fluttertoast: ^8.2.12
  http: ^1.3.0
  shared_preferences: ^2.5.3
  loading_animation_widget: ^1.3.0
  provider: ^6.1.4
  get: ^4.7.2
  persistent_bottom_nav_bar: ^6.2.1
  intl: ^0.20.2
  flutter_typeahead: ^5.2.0
  qr_flutter: ^4.1.0
  image_gallery_saver_plus: ^4.0.1
  stroke_text: ^1.0.0
  screenshot: ^3.0.0
  mobile_scanner: ^7.0.0
  dotted_line: ^3.2.3
  quickalert: ^1.1.0
  dropdown_search: ^6.0.2

  popover: ^0.3.1
  syncfusion_flutter_signaturepad: ^29.2.8
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/documents/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
